import Head from 'next/head';
import { ViewGridIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/outline';
import Image from "next/image";
import Footer from '../components/Footer';
import react, {useRef}  from 'react'

export default function Home() {

  // redirecting to google
  const searchInputRef = useRef(null);
  const search = () => {
    const term = searchInputRef.current.value;

    if (!term) return;

    window.location = `https://google.com/search?q=${term}`;
  };


  // redirecting to perfect web
  const perfect = () => {
    window.location = `https://perfects.engineering`;
  };

  const gmail = () => {
    window.location = `https://accounts.google.com/servicelogin`;
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-end text-sm text-gray-700">

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
        </div>

        {/* Icon */}
        <ViewGridIcon className="h-10 w-10 p-2 cursor-pointer" />

        {/* sign in */}
        <button onClick={gmail} className="btn sign-in">Sign in</button>
      </header>


      {/* Body */}
      <form onSubmit={e => e.preventDefault()} className="flex flex-col items-center mt-28 flex-grow w-4/5">
        <Image src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
        height={100}
        width={300}
        />

        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">

          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input 
            ref={searchInputRef}
            type="text" 
            className=" flex-grow focus:outline-none" 
          />

        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">Google Search</button>
          <button onClick={perfect} className="btn">I'm Feeling Lucky</button>
        </div>

        <div className="flex w-full p-5 items-center justify-center text-sm text-gray-700 space-x-4" >
          <p className="flex flex-wrap items-center justify-center space-x-3">Google offered in: &nbsp;
            <span className="link language">Hausa</span>
            <span className="link language">Igbo</span>
            <span className="link language">Ede Yoruba</span>
            <span className="link language">Nigerian Pidgin</span>
          </p>
        </div>

      </form>


      {/* Footer */}
      <Footer />
    </div>
  );
}
